{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [17/Sep/2020 13:42:02] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py:1596: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  self.obj[key] = _infer_fill_value(value)\n",
      "C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py:1745: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  isetter(ilocs[0], value)\n",
      "C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py:1765: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  isetter(loc, value)\n",
      "127.0.0.1 - - [17/Sep/2020 13:43:03] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [17/Sep/2020 13:43:04] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [17/Sep/2020 13:43:46] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [17/Sep/2020 13:44:43] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-09-17 13:45:15,793] ERROR in app: Exception on /tag/0 [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-97e95daa7e4e>\", line 37, in sim_tag\n",
      "    result = tc.tagData(int(stuId))\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\controller\\tag_data_controller.py\", line 67, in tagData\n",
      "    dataset=count_tag_model.tagCount(stuId,dataset)\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\model\\count_tag_model.py\", line 58, in tagCount\n",
      "    rest.loc[:,\"tagCount\"]=countKeyword\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 670, in __setitem__\n",
      "    iloc._setitem_with_indexer(indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1601, in _setitem_with_indexer\n",
      "    self._setitem_with_indexer(new_indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1667, in _setitem_with_indexer\n",
      "    \"cannot set using a multi-index \"\n",
      "ValueError: cannot set using a multi-index selection indexer with a different length than the value\n",
      "127.0.0.1 - - [17/Sep/2020 13:45:15] \"\u001b[35m\u001b[1mGET /tag/0 HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-09-17 13:46:37,271] ERROR in app: Exception on /tag/0 [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-97e95daa7e4e>\", line 37, in sim_tag\n",
      "    result = tc.tagData(int(stuId))\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\controller\\tag_data_controller.py\", line 67, in tagData\n",
      "    dataset=count_tag_model.tagCount(stuId,dataset)\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\model\\count_tag_model.py\", line 58, in tagCount\n",
      "    rest.loc[:,\"tagCount\"]=countKeyword\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 670, in __setitem__\n",
      "    iloc._setitem_with_indexer(indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1601, in _setitem_with_indexer\n",
      "    self._setitem_with_indexer(new_indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1667, in _setitem_with_indexer\n",
      "    \"cannot set using a multi-index \"\n",
      "ValueError: cannot set using a multi-index selection indexer with a different length than the value\n",
      "127.0.0.1 - - [17/Sep/2020 13:46:37] \"\u001b[35m\u001b[1mGET /tag/0 HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-09-17 13:47:31,608] ERROR in app: Exception on /tag/0 [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-97e95daa7e4e>\", line 37, in sim_tag\n",
      "    result = tc.tagData(int(stuId))\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\controller\\tag_data_controller.py\", line 67, in tagData\n",
      "    dataset=count_tag_model.tagCount(stuId,dataset)\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\model\\count_tag_model.py\", line 58, in tagCount\n",
      "    rest.loc[:,\"tagCount\"]=countKeyword\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 670, in __setitem__\n",
      "    iloc._setitem_with_indexer(indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1601, in _setitem_with_indexer\n",
      "    self._setitem_with_indexer(new_indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1667, in _setitem_with_indexer\n",
      "    \"cannot set using a multi-index \"\n",
      "ValueError: cannot set using a multi-index selection indexer with a different length than the value\n",
      "127.0.0.1 - - [17/Sep/2020 13:47:31] \"\u001b[35m\u001b[1mGET /tag/0 HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-09-17 13:49:06,824] ERROR in app: Exception on /tag/0 [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-97e95daa7e4e>\", line 37, in sim_tag\n",
      "    result = tc.tagData(int(stuId))\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\controller\\tag_data_controller.py\", line 67, in tagData\n",
      "    dataset=count_tag_model.tagCount(stuId,dataset)\n",
      "  File \"C:\\바탕 화면\\playdata\\ice\\eclipse\\Devils_Project\\dataWork\\model\\count_tag_model.py\", line 58, in tagCount\n",
      "    rest.loc[:,\"tagCount\"]=countKeyword\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 670, in __setitem__\n",
      "    iloc._setitem_with_indexer(indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1601, in _setitem_with_indexer\n",
      "    self._setitem_with_indexer(new_indexer, value)\n",
      "  File \"C:\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1667, in _setitem_with_indexer\n",
      "    \"cannot set using a multi-index \"\n",
      "ValueError: cannot set using a multi-index selection indexer with a different length than the value\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [17/Sep/2020 13:49:06] \"\u001b[35m\u001b[1mGET /tag/0 HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [17/Sep/2020 13:49:51] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [17/Sep/2020 13:50:40] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [17/Sep/2020 13:53:29] \"\u001b[37mGET /tag/10 HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "##### 서버를 위한 import\n",
    "from flask import Flask, request, jsonify, send_from_directory\n",
    "from flask_cors import CORS\n",
    "from flask_restful import Resource, Api\n",
    "from dao.reco_dao import get_reco_studio, get_ranked_studio\n",
    "\n",
    "# 다른 component import\n",
    "# from controller import data_controller as dc\n",
    "from controller import reco_controller as rc\n",
    "from controller import tag_data_controller as tc\n",
    "\n",
    "app = Flask(__name__, instance_relative_config=True)\n",
    "cors = CORS(app, resources={r'*': {'origins': '*'}})\n",
    "\n",
    "# @app.route(\"/predict\", methods = ['POST'])\n",
    "# def predict():\n",
    "#     if request.method == 'POST':\n",
    "#         img = request.files[\"image\"]\n",
    "#         result = dc.predict(img, app.instance_path)\n",
    "#         return result\n",
    "    \n",
    "@app.route(\"/recommend/<cust_id>\", methods = ['GET'])\n",
    "def main_recommend(cust_id):\n",
    "    if request.method == 'GET':\n",
    "        result = rc.get_reco_studios(int(cust_id),app.instance_path[:-9])\n",
    "        return jsonify(result)\n",
    "\n",
    "@app.route(\"/recommend\", methods = ['GET'])\n",
    "def rank_recommend():\n",
    "    if request.method == 'GET':\n",
    "        result = rc.get_ranked_studios()\n",
    "        return jsonify(result)\n",
    "\n",
    "@app.route(\"/tag/<stuId>\", methods = ['GET'])\n",
    "def sim_tag(stuId):\n",
    "    if request.method == 'GET':\n",
    "        result = tc.tagData(int(stuId))\n",
    "    return jsonify(result)\n",
    "\n",
    "# 서버 정보(as properties)\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host=\"127.0.0.1\", port=\"5000\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
